package com.viaferrataapp

// Autogenerated by @react-native/gradle-plugin — provided manually for Windows compatibility
@Suppress("unused")
object ReactNativeEntryPoint {
    @JvmField
    val packageName: String = "com.viaferrataapp"
}
